title: Ryan Berliner
email: ryan@ryanberliner.com
baseurl: ""
url: "https://ryanberliner.com"
github_username: ryanberliner
version: 2.0.1

paginate: 10
paginate_path: "/blog/page:num/"

sass:
  sass_dir: _scss
  style: compressed

markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
